services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:latest
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Johannesburg
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.phumlaniarendse.co.za`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=staging"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy-net"

volumes:
  portainer-data:
    name: portainer-data
    driver: local

networks:
  proxy-net:
    name: "proxy-net"
    external: true
